name: Data Refresh

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Update the dashboard
    runs-on: ubuntu-18.04 
    container: 
     image: benthecoder/covid19_flexdashboard
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'main'
      - name: Render Rmarkdown
        run: bash ./bash/data_refresh.sh
