name: Data Refresh

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
<<<<<<< HEAD
  render:
    name: <nameyourjob>
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Render Rmarkdown
      - run: bash ./bash/data_refresh.sh 
=======
  build:
    name: refresh the dashboard
    runs-on: ubuntu-18.04 
    container: 
     image: rkrispin/coronavirus_dashboard:dev
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with: 
          ref: 'master'
      - name: Render Rmarkdown
        run: bash ./bash/data_refresh.sh
>>>>>>> 34f190e37a3fa75a36c7c87fc6c3ecd8ecb7e426
