name: Data Refresh

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  render:
    name: <nameyourjob>
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Render Rmarkdown
      - run: bash ./bash/data_refresh.sh 

